### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by arelaxend** [kugelrund/mesh_segmentation#2]
Hi, 

Looks great! Do you have any idea why I have an infinite loop while trying the addon on a "big" mesh. Are my parameters ok ? Any idea?

<img width="1440" alt="capture d ecran 2016-08-16 a 03 10 30" src="https://cloud.githubusercontent.com/assets/8854658/17684850/243651a4-635f-11e6-9c6b-914508ff0b0b.png">

Thank you. Alexandre

**Comment by kugelrund** [comment]
I'm not aware of any infinite loops. The biggest mesh we have tried this algorithm on had ~3000 faces and that took a couple of minutes. Maybe the mesh you are trying to segment is just so big that the runtime explodes. Doesn't your cursor turn into a black icon with a percentage when segmenting the mesh?

**Comment by arelaxend** [comment]
Surprisingly the cursor does not show any percentage or any other loading image (except the normal one). Since you have developped the algorithm a long time ago, the implementation of such loading may have changed.. don't you think?

**Comment by kugelrund** [comment]
Hm that's weird, just installed the plugin on linux with Blender 2.77a and the progressbar is showing just fine. I just noticed you get the notification of non connected parts that have been seperated. I assume you have selected one of those parts and started the segmentation on that, right?

Does the segmentation work on something simpler like suzanne for you?

**Comment by arelaxend** [comment]
Finally, the progress bar is showing on my mac (for suzanne). It is a tiny white square with a number.
Yes, I remove the non connected parts.
Yes, it is working perfectly on suzanne!
The mesh on the picture is a > 20K faces and I have another mesh I am working on which is a >1M faces... Do you have idea  how to improve the algorithm to reduce its complexity so that it runs faster? Did you work on that before ?

**Comment by arelaxend** [comment]
In the code, there is:
<img width="546" alt="capture d ecran 2016-08-19 a 16 25 45" src="https://cloud.githubusercontent.com/assets/8854658/17812990/ba883218-6629-11e6-8a52-c600078c7046.png">

What do you think about improving this part ?

**Comment by kugelrund** [comment]
Ok, you got me motivated to look into this :D The part you highlighted was actually a huge bottleneck in the code, no idea what the hell i was thinking. I rewrote that section completely and its a lot faster now.

I also added console outputs that tell you what the algorithm is currently doing. You can see those messages when you choose "Window -> Toggle System Console" in Blender.

I dont think it will be able to handle 1 million faces though. As it is right now, the algorithm will have to store a (dense!) 1million by 1million matrix for the affinity matrix which sums up to 3 Terabyte if i'm not mistaken... I guess if you want to segment meshes this big you would have to find a smart way to exclude a lot of pairs of faces from the shortest path search for the affinity matrix.

I tried the algorithm on an object with 7000 faces and it took ~2.5 minutes and peaked at ~1.5GB of RAM used.

**Comment by arelaxend** [comment]
Great! I found this:

<img width="868" alt="capture d ecran 2016-08-19 a 20 07 31" src="https://cloud.githubusercontent.com/assets/8854658/17819558/c79f5a3e-6648-11e6-96a6-bc132642168c.png">

**Comment by arelaxend** [comment]
To improve the execution time, we can also use multithreading and store all the _face_center() in a separate structure. I will also look for other things. What do you think about the error ?

**Comment by arelaxend** [comment]
Great! I can see the messages in the console. That's great 👍 

- When you say, 3Tbytes, I do not understand why. To store this particular >1M faces mesh, blender uses only 64Mbytes... But, I found an alternative and you can add this alternative solution to handle big meshes. The solution is to "decimate" the object before running the segmentation (using the "decimate" operation). Thus, we just add a new input (say "Max. number of faces") which will be the input of the decimate operation. What do you think ?

- What do you think about the error ? I may have done something wrong.. When I use a basic shape (cube mesh), it works perfectly.. 

<img width="868" alt="capture d ecran 2016-08-19 a 20 07 31" src="https://cloud.githubusercontent.com/assets/8854658/17819558/c79f5a3e-6648-11e6-96a6-bc132642168c.png">

I encounter this situation with a complex mesh:
[test-with-error.blend.zip](https://github.com/kugelrund/mesh_segmentation/files/427636/test-with-error.blend.zip)

**Comment by arelaxend** [comment]
Great! This is indeed way faster! I was writing the same code and you commited. I can see the messages in the console. That's great 👍 
- What do you think about this error ? I may have done something wrong.. When I use a basic shape (cube mesh), it works perfectly.. 

<img width="868" alt="capture d ecran 2016-08-19 a 20 07 31" src="https://cloud.githubusercontent.com/assets/8854658/17819558/c79f5a3e-6648-11e6-96a6-bc132642168c.png">

I encounter this situation with a complex mesh:
[test-with-error.blend.zip](https://github.com/kugelrund/mesh_segmentation/files/427636/test-with-error.blend.zip)
- When you say, 3Tbytes, I do not agree. To store this particular >1M faces mesh, blender uses only 64Mbytes... (it is still currently too big for the algorithm so I used the classical "decimate" operation, and I am sure there is an algorithm that can work for such huge meshes and this would be awesome)
- To improve the runtime further, I thought about using multithreading (for as k-mean computation, calculation of distances, creation of the matrix). What about storing all the _face_center() in a matrix ?
- Finally, I am 100% sure that we can remove completely the for loop (where you compute the distances), and instead do the calculation using matrixes only... What do you think ?

**Comment by kugelrund** [comment]
That mesh has a couple of inconsistencies. I made the plugin be more ok with such inconsistencies and cleaned up the mesh a bit: [test-fixed.zip](https://github.com/kugelrund/mesh_segmentation/files/427949/test-fixed.zip)

With 3 clusters and small delta and eta i get a pretty decent result as you can see in the file aswell.

It would need that much memory because it is the number of faces **squared** rather than some factor times the number of faces that blender has to store

Performance can surely be improved with what you are suggesting, but really the bottleneck is the eigenvalue/-vector calculation because of the big matrices. I experimented with the limit parameter of the dijkstra algorithm a bit so that there would be a few zeros in the affinity matrix so that one could use sparse matrices for W and L. Even with low limits the amount of nonzeros didnt drop that much though and results with even quite high limits were pretty bad.

**Comment by arelaxend** [comment]
Absolutely and I will close the topic as it is working perfectly and way quicker now. As for the mesh, what did you do when you said "cleaned up" ?

**Comment by arelaxend** [comment]
Absolutely. One alternative could be to move from Scipy to MLlib and to use PIC (http://spark.apache.org/docs/latest/mllib-clustering.html#power-iteration-clustering-pic).. For the mesh, what did you do when you said "cleaned up" (I wish to reproduce the test-fixed) ?

**Comment by arelaxend** [comment]
Absolutely. One alternative could be to move from Scipy to MLlib and to use PIC (http://spark.apache.org/docs/latest/mllib-clustering.html#power-iteration-clustering-pic), don't you think ? For the mesh, what did you do when you said "cleaned up" (I wish to reproduce the test-fixed) ?

**Comment by arelaxend** [comment]
My old mesh is not working... what did you do as a "cleanup" ?

Edit: Absolutely. One good alternative could be to move from Scipy to MLlib and to use PIC (http://spark.apache.org/docs/latest/mllib-clustering.html#power-iteration-clustering-pic), don't you think ? I may start a new project on that topic, would be great to run it on a huge mesh!

**Comment by kugelrund** [comment]
To clean up the mesh i used operators like "Remove Doubles", "Delete Loose" and "Degenerate Dissolve" and fixing some broken faces by hand.

I don't know much about other clustering techniques, the course i had was about spectral clustering only so that's what we used in this project for mesh segmentation, we didn't discuss whether different clustering algorithms would give better results, so that definitely could be the case. That PIC certainly sounds interesting, good luck if you end up starting a project with it!
