### ISSUE TITLE
related work

### ISSUE THREAD

**Issue by thomas39104** [kugelrund/mesh_segmentation#3]
hi kugelrund, 
can you give a reference paper or something which you used as inspiration for this work?
i already googled and found some papers for mesh clustering by spectral clustering. 
Which would you suggest? 

Good work by the way and kind regards!

ps. maybe that one?
@inproceedings{liu2004segmentation,
  title={Segmentation of 3D meshes through spectral clustering},
  author={Liu, Rong and Zhang, Hao},
  booktitle={Computer Graphics and Applications, 2004. PG 2004. Proceedings. 12th Pacific Conference on},
  pages={298--305},
  year={2004},
  organization={IEEE}
}

**Comment by kugelrund** [comment]
Hey Thomas,

yes, that is the paper we were using, as stated in the readme. However it was given to us by the professor, so i can't help you with where to get it unfortunately. For spectral clustering in general, "U. Luxburg, A Tutorial on Spectral Clustering, Statistics and Computing, 2007." was the main reference for the course.

Have fun with looking into this topic!

**Comment by thomas39104** [comment]
Oh :+1: i was kind of blind. :dash: 

its free to read. ftp://www1.idc.ac.il/ICGF/GraphicsSeminar2006/spectralSegmentation04.pdf
