### ISSUE TITLE
Can't hit F3 to find "Segment Mesh"

### ISSUE THREAD

**Issue by Lstaras** [kugelrund/mesh_segmentation#7]
Hi,

Thank you for your code.

I install the addon and activate the add-on by ticking the box, but when i select the original cube in main view and hit F3 to type into "Segment Mesh" there is no search result.
So i confused that whether there is a limitation of segment mesh object or i have error opertation in install process.

My blender version is 2.83 with python3.74(SciPy)

Best wishes.
![2](https://user-images.githubusercontent.com/30232919/89419534-093e4a00-d764-11ea-9ccd-0c906843eec2.PNG)
![1](https://user-images.githubusercontent.com/30232919/89419554-0e9b9480-d764-11ea-89fc-fd7cfa8929aa.PNG)

**Comment by kugelrund** [comment]
Hm that's strange, does it maybe show an error in the system console (Window -> Toggle System Console)?

**Comment by Lstaras** [comment]
![image](https://user-images.githubusercontent.com/30232919/89424463-63daa480-d76a-11ea-86f7-c1bf6d782d8a.png)
Seem like no problem. Maybe my blender has some different setting or python's fault. What's your envirment of blender? Ubuntu or Windows? Environmental problems are annoying. - -;
Thanks.

**Comment by kugelrund** [comment]
I've tested on Windows with Blender 2.83, exactly what you have. I'm a bit surprised that it's showing two paths now. In your first screenshot it shows one on your E: drive in the Blender install directory. In this last screenshot its in %appdata% of your C: drive instead. Is it possible the addon is somehow installed twice, maybe an old version? Maybe that causes some conflicts. I'd suggest you try to delete the `mesh_segmentation` directory from both of those paths completely and then reinstall it.

**Comment by Lstaras** [comment]
Oh! You are right! 
Maybe there is a conflict between two position to install addon. Then it works via reinstall the blender2.83 and install the addon by zip format instead of drag code files to '2.83-scripts-addons' directory. Seem like my opertion fault :D. 
Sincere thanks.
![image](https://user-images.githubusercontent.com/30232919/89477869-f0b04d00-d7c0-11ea-8302-573f09dfc93f.png)

**Comment by ssli23** [comment]
> Oh! You are right!
> Maybe there is a conflict between two position to install addon. Then it works via reinstall the blender2.83 and install the addon by zip format instead of drag code files to '2.83-scripts-addons' directory. Seem like my opertion fault :D.
> Sincere thanks.
> ![image](https://user-images.githubusercontent.com/30232919/89477869-f0b04d00-d7c0-11ea-8302-573f09dfc93f.png)

 how to reinstall the blender2.83 and install the addon by zip format?can you give me a detailed explanation？I met the same question..

**Comment by kugelrund** [comment]
I'm not quite sure if I understand, can you be more specific maybe? The installation instructions are in the README on the main repository page https://github.com/kugelrund/mesh_segmentation#usage . In particular note the bullet point

> * Open Blender, go to "Edit -> Preferences -> Add-ons" and click on "Install...". Select the "mesh_segmentation.zip" archive that you just downloaded".
